### PR TITLE
Use `bc` for floating point addition + default cur_swap2 and max_swap2 to 0 if empty

### LINKED ISSUE #70: syntax error: invalid arithmetic operator
Full error:
```
/usr/share/sysfetch/sys/linux.sh: line 155: 23.4141: syntax error: invalid arithmetic operator (error token is ".4141")
```

```bash
cur_swap=$(sed -n '2p' /proc/swaps | awk '{print $4 / 1024}')
cur_swap2=$(sed -n '3p' /proc/swaps | awk '{print $4 / 1024}')
is $cur_swap *.* && cur_swap=${cur_swap::-3}
cur_swap=$((cur_swap + cur_swap2))
```

^ Something seems to be going wrong with the addition at the end of the script here. As far as I know, bash itself can't do floating point arithmetic, so you'd either have to round these values to integers, or pipe it to something like `bc`

### PR DESCRIPTION
**Pull request by juliavdkris**
Closes #70

### CODE REVIEW

**Comment by wick3dr0se** [comment]
I'm merging this because I believe this is a great solution and as you mentioned it's the only way to do floating point number arithmetic. bc isn't installed on Arch Linux by default, so to avoid another dependency I may use sed to strip anything after the "." instead. Then we won't need to define another variable, use another dependency or worry about more math. The original setup would work assuming that .NN is the only result but you had a .NNNN; 4 digit output from your swap. Sed is capable of removing all characters after the ".". This may be a better route, as eventually I want to drop as many external dependencies as possible. I love your solution and will be using this if sed does not work as expected. Thank you so much for your PR!

**Comment by juliavdkris** [comment]
Ah yeah, forgot `bc` isn't installed by default. You could also use `awk` instead, no need to cut off the floating point digits :)

**Comment by wick3dr0se** [comment]
@juliavdkris That would actually probably be an even better idea! I verified sed 's/\..*$//' works but awk would be great since I already use that to get the value

**Comment by wick3dr0se** [comment]
awk 'FNR == 2 {print$3 /1024} + FNR == 3 {print $3 /1024}' /proc/swaps
I got this to output 1st and 2nd swap which is actually a lot cleaner than the current method. It doesn't add the outputs together though. I would love to be able to do this in a one-liner. I'm sure I'm doing something wrong

**Comment by juliavdkris** [comment]
Only know some basic awk, so I wouldn't know of a way to oneline it tbh

There's probably a cleaner way to do it, but this works:

```bash
cur_swap1=$(awk 'FNR == 2 {print$3 /1024}' /proc/swaps)
cur_swap2=$(awk 'FNR == 3 {print$3 /1024}' /proc/swaps)
cur_swap=$(awk "BEGIN {print ${cur_swap1:-0} + ${cur_swap2:-0}}")
```

**Comment by wick3dr0se** [comment]
@juliavdkris Your *basic* awk knowledge makes this work flawlessly, so I really appreciate it!!  I've learned more about awk and the result is shorter than the original code. That's always a good thing. Thank you so much! About to push the result

**Pull request merged**
